# Generated by Django 4.1.2 on 2025-07-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0002_alter_historicalpregnancy_pe_02_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_01',
            field=models.TextField(blank=True, null=True, verbose_name='PO_01. Name of the respondent'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_02',
            field=models.TextField(blank=True, null=True, verbose_name='PO_02. Household'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_04',
            field=models.TextField(blank=True, null=True, verbose_name='PO_04. Name of the mother'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_05',
            field=models.TextField(blank=True, null=True, verbose_name='PO_05. What is her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_06',
            field=models.TextField(blank=True, null=True, verbose_name='PO_06. NRC NUMBER '),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_07',
            field=models.TextField(blank=True, null=True, verbose_name='PO_07. Nationality status?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_08',
            field=models.TextField(blank=True, null=True, verbose_name='PO_08. What is her Social Security Number?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_09',
            field=models.TextField(blank=True, null=True, verbose_name='PO_09. What is her current marital status?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_10',
            field=models.TextField(blank=True, null=True, verbose_name='PO_10. What is her Occupation?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_11A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_11A. Does she have a phone number?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_14',
            field=models.TextField(blank=True, null=True, verbose_name='PO_14. Please give me her Phone Number'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_15',
            field=models.TextField(blank=True, null=True, verbose_name='PO_15. Do you have an Antenatal card?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_17',
            field=models.TextField(blank=True, null=True, verbose_name='PO_17. Record the Name of the Facility'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_18',
            field=models.TextField(blank=True, null=True, verbose_name='PO_18. Record the First Antenatal Visit'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_19',
            field=models.TextField(blank=True, null=True, verbose_name='PO_19. Record the Last  Antenatal Visits'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_21',
            field=models.TextField(blank=True, null=True, verbose_name='PO_21. Record HIV Status'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_22',
            field=models.TextField(blank=True, null=True, verbose_name='PO_22. Record Treatment status'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_23',
            field=models.TextField(blank=True, null=True, verbose_name='PO_23. Name of the Father'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_24',
            field=models.TextField(blank=True, null=True, verbose_name='PO_24. What is his Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_25',
            field=models.TextField(blank=True, null=True, verbose_name='PO_25. NRC NUMBER'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_26',
            field=models.TextField(blank=True, null=True, verbose_name='PO_26. Nationality Status'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_27',
            field=models.TextField(blank=True, null=True, verbose_name='PO_27. What is his Social Security Number?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_28',
            field=models.TextField(blank=True, null=True, verbose_name='PO_28. What is his current marital status?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_29',
            field=models.TextField(blank=True, null=True, verbose_name='PO_29. What is his Occupation?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_31',
            field=models.TextField(blank=True, null=True, verbose_name='PO_31. Does he have a phone number?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_31A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_31A. Please give me his Phone Number'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_32',
            field=models.TextField(blank=True, null=True, verbose_name='PO_32. What is your name?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_33',
            field=models.TextField(blank=True, null=True, verbose_name='PO_33. What is your Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_34',
            field=models.TextField(blank=True, null=True, verbose_name='PO_34. Informant SEX'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_35',
            field=models.TextField(blank=True, null=True, verbose_name='PO_35. Informant Nationality'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_36',
            field=models.TextField(blank=True, null=True, verbose_name='PO_36. What is your NRC Number?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_37',
            field=models.TextField(blank=True, null=True, verbose_name='PO_37. District'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_42',
            field=models.TextField(blank=True, null=True, verbose_name='PO_42. What was the type of delivery?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_43',
            field=models.TextField(blank=True, null=True, verbose_name='PO_43. Where was the place of birth?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_44A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_44A. Enter number.'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_45',
            field=models.TextField(blank=True, null=True, verbose_name='PO_45. Was this a multiple birth?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_47B',
            field=models.TextField(blank=True, null=True, verbose_name='PO_47B. Did the baby cry, move, or breathe?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_48',
            field=models.TextField(blank=True, null=True, verbose_name='PO_48. What was the type of still  birth?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_49A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49A. Identification of baby'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_49B',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49B. Full name'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_49C',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49C. Sex of the child'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_49D',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49D. Birth weight (Kilograms)'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51A_01',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51A_01. Record of birth'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51A_02',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_02. Mother's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51A_02A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_02. Mother's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51A_03',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_03. Father's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51A_03A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_03. Father's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51A_04',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_04. Informant's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51A_04A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_04. Informant's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_02',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51B_02. Record of birth'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_03',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_03. Mother's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_03A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_03. Mother's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_04',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_04. Father's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_04A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_04. Father's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_05',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_05. Informant's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_05A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_05. Informant's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_06',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51B_06. Under 5 if no record of birth'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='PO_51B_07',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51B_07. Record of Birth'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='consent',
            field=models.TextField(blank=True, null=True, verbose_name='Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Constituency]'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='deviceid',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='[Select district]'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Enumeration Area]'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='end',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Select your name'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='gps',
            field=models.TextField(blank=True, null=True, verbose_name='Capture GPS Cordinates'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='informant',
            field=models.TextField(blank=True, null=True, verbose_name='Who is Providing the details?'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='num_children',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='po_group',
            field=models.TextField(blank=True, null=True, verbose_name='Pregnancy Outcome'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='[Select province]'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='select the name of your supervisor'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='today',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='historicalpregnancyoutcome',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Ward]'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_01',
            field=models.TextField(blank=True, null=True, verbose_name='PO_01. Name of the respondent'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_02',
            field=models.TextField(blank=True, null=True, verbose_name='PO_02. Household'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_04',
            field=models.TextField(blank=True, null=True, verbose_name='PO_04. Name of the mother'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_05',
            field=models.TextField(blank=True, null=True, verbose_name='PO_05. What is her Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_06',
            field=models.TextField(blank=True, null=True, verbose_name='PO_06. NRC NUMBER '),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_07',
            field=models.TextField(blank=True, null=True, verbose_name='PO_07. Nationality status?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_08',
            field=models.TextField(blank=True, null=True, verbose_name='PO_08. What is her Social Security Number?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_09',
            field=models.TextField(blank=True, null=True, verbose_name='PO_09. What is her current marital status?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_10',
            field=models.TextField(blank=True, null=True, verbose_name='PO_10. What is her Occupation?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_11A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_11A. Does she have a phone number?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_14',
            field=models.TextField(blank=True, null=True, verbose_name='PO_14. Please give me her Phone Number'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_15',
            field=models.TextField(blank=True, null=True, verbose_name='PO_15. Do you have an Antenatal card?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_17',
            field=models.TextField(blank=True, null=True, verbose_name='PO_17. Record the Name of the Facility'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_18',
            field=models.TextField(blank=True, null=True, verbose_name='PO_18. Record the First Antenatal Visit'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_19',
            field=models.TextField(blank=True, null=True, verbose_name='PO_19. Record the Last  Antenatal Visits'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_21',
            field=models.TextField(blank=True, null=True, verbose_name='PO_21. Record HIV Status'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_22',
            field=models.TextField(blank=True, null=True, verbose_name='PO_22. Record Treatment status'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_23',
            field=models.TextField(blank=True, null=True, verbose_name='PO_23. Name of the Father'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_24',
            field=models.TextField(blank=True, null=True, verbose_name='PO_24. What is his Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_25',
            field=models.TextField(blank=True, null=True, verbose_name='PO_25. NRC NUMBER'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_26',
            field=models.TextField(blank=True, null=True, verbose_name='PO_26. Nationality Status'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_27',
            field=models.TextField(blank=True, null=True, verbose_name='PO_27. What is his Social Security Number?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_28',
            field=models.TextField(blank=True, null=True, verbose_name='PO_28. What is his current marital status?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_29',
            field=models.TextField(blank=True, null=True, verbose_name='PO_29. What is his Occupation?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_31',
            field=models.TextField(blank=True, null=True, verbose_name='PO_31. Does he have a phone number?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_31A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_31A. Please give me his Phone Number'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_32',
            field=models.TextField(blank=True, null=True, verbose_name='PO_32. What is your name?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_33',
            field=models.TextField(blank=True, null=True, verbose_name='PO_33. What is your Date of Birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_34',
            field=models.TextField(blank=True, null=True, verbose_name='PO_34. Informant SEX'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_35',
            field=models.TextField(blank=True, null=True, verbose_name='PO_35. Informant Nationality'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_36',
            field=models.TextField(blank=True, null=True, verbose_name='PO_36. What is your NRC Number?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_37',
            field=models.TextField(blank=True, null=True, verbose_name='PO_37. District'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_42',
            field=models.TextField(blank=True, null=True, verbose_name='PO_42. What was the type of delivery?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_43',
            field=models.TextField(blank=True, null=True, verbose_name='PO_43. Where was the place of birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_44A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_44A. Enter number.'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_45',
            field=models.TextField(blank=True, null=True, verbose_name='PO_45. Was this a multiple birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_47B',
            field=models.TextField(blank=True, null=True, verbose_name='PO_47B. Did the baby cry, move, or breathe?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_48',
            field=models.TextField(blank=True, null=True, verbose_name='PO_48. What was the type of still  birth?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_49A',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49A. Identification of baby'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_49B',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49B. Full name'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_49C',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49C. Sex of the child'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_49D',
            field=models.TextField(blank=True, null=True, verbose_name='PO_49D. Birth weight (Kilograms)'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51A_01',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51A_01. Record of birth'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51A_02',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_02. Mother's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51A_02A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_02. Mother's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51A_03',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_03. Father's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51A_03A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_03. Father's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51A_04',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_04. Informant's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51A_04A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51A_04. Informant's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_02',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51B_02. Record of birth'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_03',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_03. Mother's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_03A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_03. Mother's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_04',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_04. Father's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_04A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_04. Father's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_05',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_05. Informant's NRC (Front)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_05A',
            field=models.TextField(blank=True, null=True, verbose_name="PO_51B_05. Informant's NRC (Back)"),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_06',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51B_06. Under 5 if no record of birth'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='PO_51B_07',
            field=models.TextField(blank=True, null=True, verbose_name='PO_51B_07. Record of Birth'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='consent',
            field=models.TextField(blank=True, null=True, verbose_name='Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Constituency]'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='deviceid',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='[Select district]'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Enumeration Area]'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='end',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Select your name'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='gps',
            field=models.TextField(blank=True, null=True, verbose_name='Capture GPS Cordinates'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='informant',
            field=models.TextField(blank=True, null=True, verbose_name='Who is Providing the details?'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='num_children',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='po_group',
            field=models.TextField(blank=True, null=True, verbose_name='Pregnancy Outcome'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='[Select province]'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='select the name of your supervisor'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='today',
            field=models.TextField(blank=True, null=True, verbose_name='nan'),
        ),
        migrations.AlterField(
            model_name='pregnancyoutcome',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Ward]'),
        ),
    ]
