# Generated by Django 4.1.2 on 2025-07-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0003_alter_historicalpregnancyoutcome_po_01_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpregnancyoutcome',
            name='pregnancy',
        ),
        migrations.RemoveField(
            model_name='pregnancyoutcome',
            name='pregnancy',
        ),
        migrations.AddField(
            model_name='historicalpregnancyoutcome',
            name='pregnancy_id',
            field=models.TextField(blank=True, null=True, verbose_name='Pregnancy ID'),
        ),
        migrations.AddField(
            model_name='pregnancyoutcome',
            name='pregnancy_id',
            field=models.TextField(blank=True, null=True, verbose_name='Pregnancy ID'),
        ),
    ]
