# Generated by Django 4.1.2 on 2025-07-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_data_management', '0004_remove_historicalpregnancyoutcome_pregnancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='death',
            name='age_at_death',
        ),
        migrations.RemoveField(
            model_name='death',
            name='cause_of_death',
        ),
        migrations.RemoveField(
            model_name='death',
            name='code_input',
        ),
        migrations.RemoveField(
            model_name='death',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='death',
            name='death_certificate_issued',
        ),
        migrations.RemoveField(
            model_name='death',
            name='death_occurred',
        ),
        migrations.RemoveField(
            model_name='death',
            name='deceased_name',
        ),
        migrations.RemoveField(
            model_name='death',
            name='description',
        ),
        migrations.RemoveField(
            model_name='death',
            name='end',
        ),
        migrations.RemoveField(
            model_name='death',
            name='gps_coordinates',
        ),
        migrations.RemoveField(
            model_name='death',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='death',
            name='result_other',
        ),
        migrations.RemoveField(
            model_name='death',
            name='rural_urban',
        ),
        migrations.RemoveField(
            model_name='death',
            name='sex_of_deceased',
        ),
        migrations.RemoveField(
            model_name='death',
            name='submit_time',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='age_at_death',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='cause_of_death',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='code_input',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='death_certificate_issued',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='death_occurred',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='deceased_name',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='end',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='gps_coordinates',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='result_other',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='rural_urban',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='sex_of_deceased',
        ),
        migrations.RemoveField(
            model_name='historicaldeath',
            name='submit_time',
        ),
        migrations.AddField(
            model_name='death',
            name='DE_01',
            field=models.TextField(blank=True, null=True, verbose_name='DE-01 Household ID'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_02',
            field=models.TextField(blank=True, null=True, verbose_name='DE-02 What is the name of the head of the household?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_03',
            field=models.TextField(blank=True, null=True, verbose_name='DE-03 Name of the deceased'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_04',
            field=models.TextField(blank=True, null=True, verbose_name='DE-04 Date of Birth of the deceased'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_05',
            field=models.TextField(blank=True, null=True, verbose_name='DE-05 Sex of the deceased'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_06',
            field=models.TextField(blank=True, null=True, verbose_name='DE-06 Date of death of the deceased'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_07',
            field=models.TextField(blank=True, null=True, verbose_name='DE-07 Place of death'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_08',
            field=models.TextField(blank=True, null=True, verbose_name='DE-08  NUMBER for the Deceased'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_09',
            field=models.TextField(blank=True, null=True, verbose_name='DE-09 Nationality status?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_10',
            field=models.TextField(blank=True, null=True, verbose_name="DE-10 What is ${DE-03}'s Social Security Number?"),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_11',
            field=models.TextField(blank=True, null=True, verbose_name='DE-11 Marital status of the deceased'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_12',
            field=models.TextField(blank=True, null=True, verbose_name='DE-12 Occupation of the deceased'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_13',
            field=models.TextField(blank=True, null=True, verbose_name="DE-13 What was ${DE-03}'s highest level of education?"),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_14',
            field=models.TextField(blank=True, null=True, verbose_name='DE-14 Briefly write a 10 word summary of circumstances around death (provide examples)'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_15',
            field=models.TextField(blank=True, null=True, verbose_name='DE-15 What was the cause of death?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_16',
            field=models.TextField(blank=True, null=True, verbose_name='DE-16 Did  ${DE-03} die Pregnant?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_17',
            field=models.TextField(blank=True, null=True, verbose_name='DE-17 Did  ${DE-03} die during childbirth?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_18',
            field=models.TextField(blank=True, null=True, verbose_name='DE-18 Did  ${DE-03} die within 42 days after the end of a Pregnancy or childbirth?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_19',
            field=models.TextField(blank=True, null=True, verbose_name='DE-19 Name of Informant'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_20',
            field=models.TextField(blank=True, null=True, verbose_name='DE-20 DOB of Informant'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_21',
            field=models.TextField(blank=True, null=True, verbose_name='DE-21 Sex of Infomant'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_22',
            field=models.TextField(blank=True, null=True, verbose_name='DE-22 Residential Address of Informant'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_23',
            field=models.TextField(blank=True, null=True, verbose_name='DE-23 NRC Number'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_24',
            field=models.TextField(blank=True, null=True, verbose_name='DE-24 Nationality'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_25',
            field=models.TextField(blank=True, null=True, verbose_name='DE-25 What is your relationship to the deceased?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_26',
            field=models.TextField(blank=True, null=True, verbose_name='DE-26 Please give me your telephone contact number'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_27',
            field=models.TextField(blank=True, null=True, verbose_name='DE-27 When is the appropriate day for the verbal autopsy interview?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_28',
            field=models.TextField(blank=True, null=True, verbose_name='DE-28 Please provide me the name of the contact person'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_29',
            field=models.TextField(blank=True, null=True, verbose_name='DE-29 Please Provide a telephone contact number of the contact person'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_30',
            field=models.TextField(blank=True, null=True, verbose_name="DE-30 Did you register  ${DE-03}'s death with DNRPC ?"),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_31',
            field=models.TextField(blank=True, null=True, verbose_name='DE-31 Do you know the procedure for death Registration and/or Certification as required by DNRPC ?'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_32_Original_nrc_of_the_deceased',
            field=models.TextField(blank=True, null=True, verbose_name='ORIGINAL NRC OF THE DECEASED'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_32_affidavit_for_less_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='AFFIDAVIT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_32_burial_permit',
            field=models.TextField(blank=True, null=True, verbose_name='BURIAL DERMIT'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_32_coroners_report',
            field=models.TextField(blank=True, null=True, verbose_name='CORONERS REPORT'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_32_mccd',
            field=models.TextField(blank=True, null=True, verbose_name='MCCD'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_32_police_report_loss_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='POLICE REPORT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_33_affidavit_loss_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='AFFIDAVIT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_33_bid_form',
            field=models.TextField(blank=True, null=True, verbose_name='BID form'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_33_informant_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='CODY OF NRC FOR THE INFORMANT'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_33_letter_from_a_traditional_leader',
            field=models.TextField(blank=True, null=True, verbose_name='LETTER FROM A TRADITIONAL LEADER'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_33_original_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='ORIGINAL NRC OF THE DECEASED'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_33_police_report_loss_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='POLICE REPORT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='death',
            name='DE_34',
            field=models.TextField(blank=True, null=True, verbose_name='DE-34 Capture GPS Cordinates for the Household'),
        ),
        migrations.AddField(
            model_name='death',
            name='informant',
            field=models.TextField(blank=True, null=True, verbose_name='Who is providing the details?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_01',
            field=models.TextField(blank=True, null=True, verbose_name='DE-01 Household ID'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_02',
            field=models.TextField(blank=True, null=True, verbose_name='DE-02 What is the name of the head of the household?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_03',
            field=models.TextField(blank=True, null=True, verbose_name='DE-03 Name of the deceased'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_04',
            field=models.TextField(blank=True, null=True, verbose_name='DE-04 Date of Birth of the deceased'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_05',
            field=models.TextField(blank=True, null=True, verbose_name='DE-05 Sex of the deceased'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_06',
            field=models.TextField(blank=True, null=True, verbose_name='DE-06 Date of death of the deceased'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_07',
            field=models.TextField(blank=True, null=True, verbose_name='DE-07 Place of death'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_08',
            field=models.TextField(blank=True, null=True, verbose_name='DE-08  NUMBER for the Deceased'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_09',
            field=models.TextField(blank=True, null=True, verbose_name='DE-09 Nationality status?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_10',
            field=models.TextField(blank=True, null=True, verbose_name="DE-10 What is ${DE-03}'s Social Security Number?"),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_11',
            field=models.TextField(blank=True, null=True, verbose_name='DE-11 Marital status of the deceased'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_12',
            field=models.TextField(blank=True, null=True, verbose_name='DE-12 Occupation of the deceased'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_13',
            field=models.TextField(blank=True, null=True, verbose_name="DE-13 What was ${DE-03}'s highest level of education?"),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_14',
            field=models.TextField(blank=True, null=True, verbose_name='DE-14 Briefly write a 10 word summary of circumstances around death (provide examples)'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_15',
            field=models.TextField(blank=True, null=True, verbose_name='DE-15 What was the cause of death?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_16',
            field=models.TextField(blank=True, null=True, verbose_name='DE-16 Did  ${DE-03} die Pregnant?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_17',
            field=models.TextField(blank=True, null=True, verbose_name='DE-17 Did  ${DE-03} die during childbirth?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_18',
            field=models.TextField(blank=True, null=True, verbose_name='DE-18 Did  ${DE-03} die within 42 days after the end of a Pregnancy or childbirth?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_19',
            field=models.TextField(blank=True, null=True, verbose_name='DE-19 Name of Informant'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_20',
            field=models.TextField(blank=True, null=True, verbose_name='DE-20 DOB of Informant'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_21',
            field=models.TextField(blank=True, null=True, verbose_name='DE-21 Sex of Infomant'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_22',
            field=models.TextField(blank=True, null=True, verbose_name='DE-22 Residential Address of Informant'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_23',
            field=models.TextField(blank=True, null=True, verbose_name='DE-23 NRC Number'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_24',
            field=models.TextField(blank=True, null=True, verbose_name='DE-24 Nationality'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_25',
            field=models.TextField(blank=True, null=True, verbose_name='DE-25 What is your relationship to the deceased?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_26',
            field=models.TextField(blank=True, null=True, verbose_name='DE-26 Please give me your telephone contact number'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_27',
            field=models.TextField(blank=True, null=True, verbose_name='DE-27 When is the appropriate day for the verbal autopsy interview?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_28',
            field=models.TextField(blank=True, null=True, verbose_name='DE-28 Please provide me the name of the contact person'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_29',
            field=models.TextField(blank=True, null=True, verbose_name='DE-29 Please Provide a telephone contact number of the contact person'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_30',
            field=models.TextField(blank=True, null=True, verbose_name="DE-30 Did you register  ${DE-03}'s death with DNRPC ?"),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_31',
            field=models.TextField(blank=True, null=True, verbose_name='DE-31 Do you know the procedure for death Registration and/or Certification as required by DNRPC ?'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_32_Original_nrc_of_the_deceased',
            field=models.TextField(blank=True, null=True, verbose_name='ORIGINAL NRC OF THE DECEASED'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_32_affidavit_for_less_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='AFFIDAVIT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_32_burial_permit',
            field=models.TextField(blank=True, null=True, verbose_name='BURIAL DERMIT'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_32_coroners_report',
            field=models.TextField(blank=True, null=True, verbose_name='CORONERS REPORT'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_32_mccd',
            field=models.TextField(blank=True, null=True, verbose_name='MCCD'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_32_police_report_loss_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='POLICE REPORT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_33_affidavit_loss_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='AFFIDAVIT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_33_bid_form',
            field=models.TextField(blank=True, null=True, verbose_name='BID form'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_33_informant_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='CODY OF NRC FOR THE INFORMANT'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_33_letter_from_a_traditional_leader',
            field=models.TextField(blank=True, null=True, verbose_name='LETTER FROM A TRADITIONAL LEADER'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_33_original_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='ORIGINAL NRC OF THE DECEASED'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_33_police_report_loss_of_nrc',
            field=models.TextField(blank=True, null=True, verbose_name='POLICE REPORT FOR LOSS OF NRC'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='DE_34',
            field=models.TextField(blank=True, null=True, verbose_name='DE-34 Capture GPS Cordinates for the Household'),
        ),
        migrations.AddField(
            model_name='historicaldeath',
            name='informant',
            field=models.TextField(blank=True, null=True, verbose_name='Who is providing the details?'),
        ),
        migrations.AlterField(
            model_name='death',
            name='consent',
            field=models.TextField(blank=True, null=True, verbose_name='Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='death',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Constituency]'),
        ),
        migrations.AlterField(
            model_name='death',
            name='deviceid',
            field=models.TextField(blank=True, null=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='death',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='[Select district]'),
        ),
        migrations.AlterField(
            model_name='death',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Enumeration Area]'),
        ),
        migrations.AlterField(
            model_name='death',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Select your name'),
        ),
        migrations.AlterField(
            model_name='death',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='[Select province]'),
        ),
        migrations.AlterField(
            model_name='death',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='Form Start Time'),
        ),
        migrations.AlterField(
            model_name='death',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='Select the name of your supervisor'),
        ),
        migrations.AlterField(
            model_name='death',
            name='today',
            field=models.TextField(blank=True, null=True, verbose_name='Date Recorded'),
        ),
        migrations.AlterField(
            model_name='death',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Ward]'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='consent',
            field=models.TextField(blank=True, null=True, verbose_name='Did respondent give consent?'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='constituency',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Constituency]'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='deviceid',
            field=models.TextField(blank=True, null=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='district',
            field=models.TextField(blank=True, null=True, verbose_name='[Select district]'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='ea',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Enumeration Area]'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='enumerator',
            field=models.TextField(blank=True, null=True, verbose_name='Select your name'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='province',
            field=models.TextField(blank=True, null=True, verbose_name='[Select province]'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='start',
            field=models.TextField(blank=True, null=True, verbose_name='Form Start Time'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='supervisor',
            field=models.TextField(blank=True, null=True, verbose_name='Select the name of your supervisor'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='today',
            field=models.TextField(blank=True, null=True, verbose_name='Date Recorded'),
        ),
        migrations.AlterField(
            model_name='historicaldeath',
            name='ward',
            field=models.TextField(blank=True, null=True, verbose_name='[Select Ward]'),
        ),
    ]
